USE [MLBPitchClassification]
GO


SELECT TOP (1000)
    [ID]
    ,[MLBGameID]
    ,[ParkID]
    ,[ParkName]
    ,[ParkCity]
    ,[ParkState]
    ,[ParkLeague]
    ,[PlayGUID_Pitch]
    ,[PlayGUID_Event]
    ,[Num]
    ,[Des_Pitch]
    ,[DesEs_Pitch]
    ,[DesEs_Event]
    ,[Des_Event]
    ,[InningNum]
    ,[InningHalf]
    ,[EventEs]
    ,[Event]
    ,[AwayTeamRuns]
    ,[HomeTeamRuns]
    ,[Balls]
    ,[Strikes]
    ,[Outs]
    ,[Pitcher]
    ,[PitcherThrows]
    ,[Batter]
    ,[BatterHeight]
    ,[BatterStand]
    ,[StartTFS]
    ,[StartTFSZulu]
    ,[EndTFSZulu]
    ,[ax]
    ,[ay]
    ,[az]
    ,[BreakAngle]
    ,[BreakLength]
    ,[Break_y]
    ,[StartSpeed]
    ,[EndSpeed]
    ,[pfx_x]
    ,[pfx_z]
    ,[px]
    ,[pz]
    ,[SpinDir]
    ,[SpinRate]
    ,[sv_id]
    ,[sz_bot]
    ,[sz_top]
    ,[vx0]
    ,[vy0]
    ,[vz0]
    ,[x]
    ,[x0]
    ,[y]
    ,[y0]
    ,[z0]
    ,[Zone]
    ,[Nasty]
    ,[PitchType]
    ,[CC]
    ,[Code]
    ,[MT]
    ,[TFS]
    ,[TFSZulu]
    ,[Type]
    ,[TypeConfidence]
FROM
    [MLBPitchClassification].[dbo].[MLBPitch_2019]





-- Differences by park
IF ( SELECT OBJECT_ID('tempdb.dbo.#PitchFX') ) IS NOT NULL
    DROP TABLE #PitchFX
GO

SELECT
    [ID]
    ,[MLBGameID]
    ,[ParkID]
    ,[ParkName]
    ,[ParkCity]
    ,[ParkState]
    ,[ParkLeague]
    ,[Pitcher]
    ,[ax]
    ,[ay]
    ,[az]
    ,[BreakAngle]
    ,[BreakLength]
    ,[Break_y]
    ,[StartSpeed]
    ,[EndSpeed]
    ,[pfx_x]
    ,[pfx_z]
    ,[px]
    ,[pz]
    ,[vx0]
    ,[vy0]
    ,[vz0]
    ,[x]
    ,[x0]
    ,[y]
    ,[y0]
    ,[z0]
INTO
    #PitchFX
FROM
    [dbo].[MLBPitch_2019]
ORDER BY
    [ID]


SELECT TOP 1000  * FROM #PitchFX


SELECT
	[Pitcher] AS [PitcherID]
	,[ParkID]
	,p.[fullName] AS [PitcherName]
    ,[ParkName]
    ,[ParkCity]
    ,[ParkState]
	,COUNT(*) AS [n]
    ,MIN([x0]) [x0_Min]
    ,MAX([x0]) [x0_Max]
    ,AVG([x0]) [x0_Avg]
    ,STDEVP([x0]) [x0_StDev]
    ,MIN([y0]) [y0_Min]
    ,MAX([y0]) [y0_Max]
    ,AVG([y0]) [y0_Avg]
    ,STDEVP([y0]) [y0_StDev]
    ,MIN([z0]) [z0_Min]
    ,MAX([z0]) [z0_Max]
    ,AVG([z0]) [z0_Avg]
    ,STDEVP([z0]) [z0_StDev]
    ,MIN([vx0]) [vx0_Min]
    ,MAX([vx0]) [vx0_Max]
    ,AVG([vx0]) [vx0_Avg]
    ,STDEVP([vx0]) [vx0_StDev]
    ,MIN([vy0]) [vy0_Min]
    ,MAX([vy0]) [vy0_Max]
    ,AVG([vy0]) [vy0_Avg]
    ,STDEVP([vy0]) [vy0_StDev]
    ,MIN([vz0]) [vz0_Min]
    ,MAX([vz0]) [vz0_Max]
    ,AVG([vz0]) [vz0_Avg]
    ,STDEVP([vz0]) [vz0_StDev]
    ,MIN([ax]) [ax_Min]
    ,MAX([ax]) [ax_Max]
    ,AVG([ax]) [ax_Avg]
    ,STDEVP([ax]) [ax_StDev]
    ,MIN([ay]) [ay_Min]
    ,MAX([ay]) [ay_Max]
    ,AVG([ay]) [ay_Avg]
    ,STDEVP([ay]) [ay_StDev]
    ,MIN([az]) [az_Min]
    ,MAX([az]) [az_Max]
    ,AVG([az]) [az_Avg]
    ,STDEVP([az]) [az_StDev]
    ,MIN([px]) [px_Min]
    ,MAX([px]) [px_Max]
    ,AVG([px]) [px_Avg]
    ,STDEVP([px]) [px_StDev]
    ,MIN([pz]) [pz_Min]
    ,MAX([pz]) [pz_Max]
    ,AVG([pz]) [pz_Avg]
    ,STDEVP([pz]) [pz_StDev]
    ,MIN([BreakAngle]) [BreakAngle_Min]
    ,MAX([BreakAngle]) [BreakAngle_Max]
    ,AVG([BreakAngle]) [BreakAngle_Avg]
    ,STDEVP([BreakAngle]) [BreakAngle_StDev]
    ,MIN([BreakLength]) [BreakLength_Min]
    ,MAX([BreakLength]) [BreakLength_Max]
    ,AVG([BreakLength]) [BreakLength_Avg]
    ,STDEVP([BreakLength]) [BreakLength_StDev]
    ,MIN([Break_y]) [Break_y_Min]
    ,MAX([Break_y]) [Break_y_Max]
    ,AVG([Break_y]) [Break_y_Avg]
    ,STDEVP([Break_y]) [Break_y_StDev]
    ,MIN([pfx_x]) [pfx_x_Min]
    ,MAX([pfx_x]) [pfx_x_Max]
    ,AVG([pfx_x]) [pfx_x_Avg]
    ,STDEVP([pfx_x]) [pfx_x_StDev]
    ,MIN([pfx_z]) [pfx_z_Min]
    ,MAX([pfx_z]) [pfx_z_Max]
    ,AVG([pfx_z]) [pfx_z_Avg]
    ,STDEVP([pfx_z]) [pfx_z_StDev]
    ,MIN([StartSpeed]) [StartSpeed_Min]
    ,MAX([StartSpeed]) [StartSpeed_Max]
    ,AVG([StartSpeed]) [StartSpeed_Avg]
    ,STDEVP([StartSpeed]) [StartSpeed_StDev]
    ,MIN([EndSpeed]) [EndSpeed_Min]
    ,MAX([EndSpeed]) [EndSpeed_Max]
    ,AVG([EndSpeed]) [EndSpeed_Avg]
    ,STDEVP([EndSpeed]) [EndSpeed_StDev]
INTO
	[dbo].[MLBPitch_2019_SummByPark]
FROM
    #PitchFX pfx
	JOIN [PitchFX].[stg].[Player] p ON pfx.[Pitcher] = p.[id]
GROUP BY
	[Pitcher]
	,[ParkID]
	,p.[fullName]
    ,[ParkName]
    ,[ParkCity]
    ,[ParkState]
ORDER BY
	p.[FullName]
	,[ParkName]
GO





SELECT
	[MLBGameID]
	,[Pitcher] AS [PitcherID]
	,[ParkID]
	,p.[fullName] AS [PitcherName]
    ,[ParkName]
    ,[ParkCity]
    ,[ParkState]
	,COUNT(*) AS [n]
    ,MIN([x0]) [x0_Min]
    ,MAX([x0]) [x0_Max]
    ,AVG([x0]) [x0_Avg]
    ,STDEV([x0]) [x0_StDev]
    ,MIN([y0]) [y0_Min]
    ,MAX([y0]) [y0_Max]
    ,AVG([y0]) [y0_Avg]
    ,STDEV([y0]) [y0_StDev]
    ,MIN([z0]) [z0_Min]
    ,MAX([z0]) [z0_Max]
    ,AVG([z0]) [z0_Avg]
    ,STDEV([z0]) [z0_StDev]
    ,MIN([vx0]) [vx0_Min]
    ,MAX([vx0]) [vx0_Max]
    ,AVG([vx0]) [vx0_Avg]
    ,STDEV([vx0]) [vx0_StDev]
    ,MIN([vy0]) [vy0_Min]
    ,MAX([vy0]) [vy0_Max]
    ,AVG([vy0]) [vy0_Avg]
    ,STDEV([vy0]) [vy0_StDev]
    ,MIN([vz0]) [vz0_Min]
    ,MAX([vz0]) [vz0_Max]
    ,AVG([vz0]) [vz0_Avg]
    ,STDEV([vz0]) [vz0_StDev]
    ,MIN([ax]) [ax_Min]
    ,MAX([ax]) [ax_Max]
    ,AVG([ax]) [ax_Avg]
    ,STDEV([ax]) [ax_StDev]
    ,MIN([ay]) [ay_Min]
    ,MAX([ay]) [ay_Max]
    ,AVG([ay]) [ay_Avg]
    ,STDEV([ay]) [ay_StDev]
    ,MIN([az]) [az_Min]
    ,MAX([az]) [az_Max]
    ,AVG([az]) [az_Avg]
    ,STDEV([az]) [az_StDev]
    ,MIN([px]) [px_Min]
    ,MAX([px]) [px_Max]
    ,AVG([px]) [px_Avg]
    ,STDEV([px]) [px_StDev]
    ,MIN([pz]) [pz_Min]
    ,MAX([pz]) [pz_Max]
    ,AVG([pz]) [pz_Avg]
    ,STDEV([pz]) [pz_StDev]
    ,MIN([BreakAngle]) [BreakAngle_Min]
    ,MAX([BreakAngle]) [BreakAngle_Max]
    ,AVG([BreakAngle]) [BreakAngle_Avg]
    ,STDEV([BreakAngle]) [BreakAngle_StDev]
    ,MIN([BreakLength]) [BreakLength_Min]
    ,MAX([BreakLength]) [BreakLength_Max]
    ,AVG([BreakLength]) [BreakLength_Avg]
    ,STDEV([BreakLength]) [BreakLength_StDev]
    ,MIN([Break_y]) [Break_y_Min]
    ,MAX([Break_y]) [Break_y_Max]
    ,AVG([Break_y]) [Break_y_Avg]
    ,STDEV([Break_y]) [Break_y_StDev]
    ,MIN([pfx_x]) [pfx_x_Min]
    ,MAX([pfx_x]) [pfx_x_Max]
    ,AVG([pfx_x]) [pfx_x_Avg]
    ,STDEV([pfx_x]) [pfx_x_StDev]
    ,MIN([pfx_z]) [pfx_z_Min]
    ,MAX([pfx_z]) [pfx_z_Max]
    ,AVG([pfx_z]) [pfx_z_Avg]
    ,STDEV([pfx_z]) [pfx_z_StDev]
    ,MIN([StartSpeed]) [StartSpeed_Min]
    ,MAX([StartSpeed]) [StartSpeed_Max]
    ,AVG([StartSpeed]) [StartSpeed_Avg]
    ,STDEV([StartSpeed]) [StartSpeed_StDev]
    ,MIN([EndSpeed]) [EndSpeed_Min]
    ,MAX([EndSpeed]) [EndSpeed_Max]
    ,AVG([EndSpeed]) [EndSpeed_Avg]
    ,STDEV([EndSpeed]) [EndSpeed_StDev]
INTO
	[dbo].[MLBPitch_2019_SummByGame]
FROM
    #PitchFX pfx
	JOIN [PitchFX].[stg].[Player] p ON pfx.[Pitcher] = p.[id]
GROUP BY
	[MLBGameID]
	,[Pitcher]
	,[ParkID]
	,p.[fullName]
    ,[ParkName]
    ,[ParkCity]
    ,[ParkState]
ORDER BY
	[MLBGameID]
	,p.[FullName]
	,[ParkName]
GO
	

